# Generated by Django 5.0.4 on 2024-04-29 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificacion', '0005_remove_calificacion_fk_id_cursada_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('opinion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='fk_id_usuario',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='opinion',
            old_name='fk_id_cursada',
            new_name='curso',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='opinion',
            name='calificacion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='opiniones_calificacion', to='calificacion.calificacion'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='contenido',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='opinion',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='opinion',
            name='titulo',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
