# Generated by Django 4.2.6 on 2023-11-10 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calificacion', '0004_alter_calificacion_fk_id_cursada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_calificacion', models.CharField(blank=True, choices=[('Profesor', 'Profesor'), ('Institución', 'Institución'), ('Carrera', 'Carrera'), ('Materia', 'Materia')], default='Institución', max_length=50, null=True)),
                ('fk_id_calificacion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='calificacion.calificacion')),
            ],
        ),
    ]
