# Generated by Django 4.2.5 on 2023-09-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='nota',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
