# Generated by Django 4.2.6 on 2023-11-10 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calificacion', '0001_initial'),
        ('cursada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='fk_id_cursada',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_cursada', to='cursada.cursada'),
        ),
    ]
