# Generated by Django 5.0.4 on 2024-04-29 07:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificacion', '0004_alter_calificacion_fk_id_cursada_and_more'),
        ('cursada', '0003_cursada_titulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='fk_id_cursada',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='fk_id_usuario',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificacion_autor_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='curso',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificacion_curso', to='cursada.cursada'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='calificacion_num',
            field=models.PositiveIntegerField(default=5, help_text='Puntuación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
