# Generated by Django 4.2.6 on 2024-05-02 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calificacion', '0005_remove_calificacion_fk_id_cursada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificacion_autor', to=settings.AUTH_USER_MODEL),
        ),
    ]
